version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: akylbek
      POSTGRES_PASSWORD: asdfghjkl;'
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: akylbek
      DB_PASSWORD: asdfghjkl;'
      DB_NAME: user_service_db

volumes:
  db_data:
